add_product_to_stock:
  name: Add Product To Stock
  description: Adds a given amount of a product to the stock
  fields:
    product_id:
      name: Product Id
      example: '3'
      required: true
      description: The id of the product to add to stock
      selector:
        text:
    amount:
      name: Amount
      description: The amount to add to stock
      required: true
      example: 3
      default: 1
      selector:
        number:
          min: 1
          max: 1000
          mode: box
    price:
      name: Price
      example: 1.99
      description: The purchase price per purchase quantity unit of the added product
      selector:
        text:

open_product:
  name: Open Product
  description: Opens a given amount of a product in stock
  fields:
    product_id:
      name: Product Id
      example: '3'
      required: true
      description: The id of the product to open
      selector:
        text:
    amount:
      name: Amount
      example: 1
      required: true
      description: The amount to open
      selector:
        number:
          min: 1
          max: 1000
          mode: box
    allow_subproduct_substitution:
      name: Subproduct substitution
      description: If subproduct substitution is allowed
      example: false
      default: false
      selector:
        boolean:

consume_product_from_stock:
  name: Consume Product From Stock
  description: Consumes a given amount of a product to the stock
  fields:
    product_id:
      name: Product Id
      example: '3'
      required: true
      description: The id of the product to consume
      selector:
        text:
    amount:
      name: Amount
      example: 3
      required: true
      description: The amount to consume
      selector:
        number:
          min: 1
          max: 1000
          mode: box
    spoiled:
      name: Spoiled
      description: If the product was removed because of spoilage
      example: false
      default: false
      selector:
        boolean:
    allow_subproduct_substitution:
      name: Subproduct substitution
      description: If subproduct substitution is allowed
      example: false
      default: false
      selector:
        boolean:
    transaction_type:
      name: Transaction Type
      description: The type of the transaction.
      required: true
      example: "CONSUME"
      default: "CONSUME"
      selector:
        select:
          options:
            - "CONSUME"
            - "PURCHASE"
            - "INVENTORY_CORRECTION"
            - "PRODUCT_OPENED"
execute_chore:
  name: Execute Chore
  description: Executes the given chore with an optional timestamp and executor
  fields:
    chore_id:
      name: Chore Id
      example: '3'
      required: true
      description: The id of the chore to execute
      selector:
        text:
    done_by:
      name: User Id
      example: '0'
      required: true
      description: The id of the user who executed the chore
      selector:
        text:
    track_execution_now:
      name: Execution now
      example: false
      default: false
      required: false
      description: If the chore execution should be tracked with the time now
      selector:
        boolean:
    skipped:
      name: Skip execution
      description: Skip next chore schedule
      example: false
      default: false
      selector:
        boolean:

complete_task:
  name: Complete Task
  description: Completes the given task
  fields:
    task_id:
      name: Task Id
      example: '3'
      required: true
      description: The id of the task to complete
      selector:
        text:

add_generic:
  name: Add Generic
  description: Adds a single object of the given entity type
  fields:
    entity_type:
      name: Entity Type
      description: The type of entity you like to add.
      required: true
      example: 'tasks'
      default: 'tasks'
      selector:
        select:
          options:
            - "products"
            - "chores"
            - "product_barcodes"
            - "batteries"
            - "locations"
            - "quantity_units"
            - "quantity_unit_conversions"
            - "shopping_list"
            - "shopping_lists"
            - "shopping_locations"
            - "recipes"
            - "recipes_pos"
            - "recipes_nestings"
            - "tasks"
            - "task_categories"
            - "product_groups"
            - "equipment"
            - "userfields"
            - "userentities"
            - "userobjects"
            - "meal_plan"
    data:
      name: Data
      description: "JSON object with what data you want to add (yaml format also works). See Grocy api documentation on Generic entity interactions: https://demo.grocy.info/api"
      required: true
      default: {"name": "Task name", "due_date": "2021-05-21"}
      selector:
        object:


update_generic:
  name: Update Generic
  description: Edits a single object of the given entity type
  fields:
    entity_type:
      name: Entity Type
      description: The type of entity you like to update.
      required: true
      example: 'tasks'
      default: 'tasks'
      selector:
        select:
          options:
            - "products"
            - "chores"
            - "product_barcodes"
            - "batteries"
            - "locations"
            - "quantity_units"
            - "quantity_unit_conversions"
            - "shopping_list"
            - "shopping_lists"
            - "shopping_locations"
            - "recipes"
            - "recipes_pos"
            - "recipes_nestings"
            - "tasks"
            - "task_categories"
            - "product_groups"
            - "equipment"
            - "userfields"
            - "userentities"
            - "userobjects"
            - "meal_plan"

    object_id:
      name: Object ID
      description: The ID of the entity to update.
      required: true
      example: '1'
      selector:
        text:

    data:
      name: Data
      description: "JSON object with what data you want to update (yaml format also works). See Grocy api documentation on Generic entity interactions: https://demo.grocy.info/api"
      required: true
      default: {"name": "Task name", "due_date": "2021-05-21"}
      selector:
        object:


delete_generic:
  name: Delete Generic
  description: Deletes a single object of the given entity type
  fields:
    entity_type:
      name: Entity Type
      description: The type of entity to be deleted.
      required: true
      example: 'tasks'
      default: 'tasks'
      selector:
        select:
          options:
            - "products"
            - "chores"
            - "product_barcodes"
            - "batteries"
            - "locations"
            - "quantity_units"
            - "quantity_unit_conversions"
            - "shopping_list"
            - "shopping_lists"
            - "shopping_locations"
            - "recipes"
            - "recipes_pos"
            - "recipes_nestings"
            - "tasks"
            - "task_categories"
            - "product_groups"
            - "equipment"
            - "userfields"
            - "userentities"
            - "userobjects"
            - "meal_plan"

    object_id:
      name: Object ID
      description: The ID of the entity to delete.
      required: true
      example: '1'
      selector:
        text:


consume_recipe:
  name: Consume Recipe
  description: Consumes the given recipe
  fields:
    recipe_id:
      name: Recipe Id
      example: '3'
      required: true
      description: The id of the recipe to consume
      selector:
        text:

track_battery:
  name: Track Battery
  description: Tracks the given battery
  fields:
    battery_id:
      name: Battery Id
      example: '1'
      required: true
      description: The id of the battery
      selector:
        text:

add_missing_products_to_shopping_list:
  name: Add Missing Products to Shopping List
  description: Adds currently missing products to the given shopping list.
  fields:
    list_id:
      name: List Id
      example: '1'
      required: false
      description: The id of the shopping list to be added to.
      selector:
        text:

remove_product_in_shopping_list:
  name: Remove Product in Shopping List
  description: Removes a product in the given shopping list.
  fields:
    list_id:
      name: List Id
      example: '1'
      required: false
      description: The id of the shopping list to be added to.
      selector:
        text:
    product_id:
      name: Product Id
      example: '3'
      required: true
      description: The id of the product to remove
      selector:
        text:
    amount:
      name: Amount
      example: 3
      required: true
      description: The amount to remove
      selector:
        number:
          min: 1
          max: 1000
          mode: box
